### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by blippy** [ZigEmbeddedGroup/regz#83]
Trying to build with zig 0.8.0:
```
./build.zig:18:30: error: container 'std.build' has no member called 'OptionsStep'
    build_options: *std.build.OptionsStep,
                             ^
./build.zig:96:22: note: referenced here
    const regz = Regz.create(b, .{
                     ^
/home/pi/tools/zig-linux-x86_64-0.8.0/lib/std/special/build_runner.zig:158:24: note: referenced here
        .ErrorUnion => try root.build(builder),

```

Trying to build with zig 0.10.1:
```
/home/pi/src/regz/.gyro/zig-libxml2-mitchellh-github.com-366b26b0/pkg/libxml2.zig:167:19: error: no field named 'type' in struct 'builtin.Type.StructField'
        if (field.type == bool and @field(opts, field.name)) {
                  ^~~~
/home/pi/src/zig-linux-x86_64-0.10.1/lib/std/builtin.zig:283:29: note: struct declared here
    pub const StructField = struct {
                            ^~~~~~
referenced by:
    create: /home/pi/src/regz/build.zig:30:28
    build: /home/pi/src/regz/build.zig:96:22
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

```

**Comment by mattnite** [comment]
Right now you need to use zig master, I will update the readme later tonight
